In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("max_row", None) # 행 수 제한 해제
pd.set_option("max_column", None) # 열 수 제한 해제
%matplotlib inline

# Load Data

In [27]:
rawData = pd.read_csv('data/asos_253_20120603_20220602.csv')

rawData.tail(3)

,Unnamed: 0,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,hr1MaxRn,hr1MaxRnHrmt,sumRnDur,sumRn,maxInsWs,maxInsWsWd,maxInsWsHrmt,maxWs,maxWsWd,maxWsHrmt,avgWs,hr24SumRws,maxWd,avgTd,minRhm,minRhmHrmt,avgRhm,avgPv,avgPa,maxPs,maxPsHrmt,minPs,minPsHrmt,avgPs,ssDur,sumSsHr,hr1MaxIcsrHrmt,hr1MaxIcsr,sumGsr,ddMefs,ddMefsHrmt,ddMes,ddMesHrmt,sumDpthFhsc,avgTca,avgLmac,avgTs,minTg,avgCm5Te,avgCm10Te,avgCm20Te,avgCm30Te,avgM05Te,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur
3649,3649,253,김해시,2022-05-31,22.6,18.2,603,29.1,1303,NaN,NaN,NaN,NaN,NaN,NaN,10.9,160,1637,6.9,160,1636,2.4,2046,320.0,8.8,18,1309,44.4,11.6,1001.6,1010.5,2335.0,1003.0,30.0,1007.8,14.4,12.9,1100.0,3.48,29.06,NaN,NaN,NaN,NaN,NaN,1.8,0.0,28.5,13.8,25.6,25.3,24.7,24.0,NaN,NaN,NaN,NaN,NaN,6.5,9.3,NaN,NaN,NaN
3650,3650,253,김해시,2022-06-01,22.2,17.5,512,29.5,1145,NaN,NaN,NaN,NaN,NaN,NaN,8.1,180,1342,4.8,160,1607,1.8,1542,160.0,11.1,21,1335,52.5,13.5,1000.9,1010.2,1.0,1004.7,1712.0,1007.1,14.4,11.2,1300.0,3.49,26.86,NaN,NaN,NaN,NaN,NaN,5.6,0.4,28.9,14.1,26.1,25.7,24.9,24.2,NaN,NaN,NaN,NaN,NaN,5.9,8.4,NaN,NaN,NaN
3651,3651,253,김해시,2022-06-02,21.8,16.6,544,27.7,1328,NaN,NaN,NaN,NaN,NaN,NaN,8.2,160,1454,5.4,160,1452,1.5,1327,110.0,14.9,47,1615,66.1,17.0,1001.0,1008.4,805.0,1005.7,1622.0,1007.2,14.4,13.0,1200.0,3.61,29.41,NaN,NaN,NaN,NaN,NaN,0.0,0.0,29.1,12.8,26.2,25.9,25.1,24.4,NaN,NaN,NaN,NaN,NaN,5.4,7.8,NaN,NaN,NaN

## Check Missing Values

In [28]:
rawData.isna().sum()

Unnamed: 0           0
stnId                0
stnNm                0
tm                   0
avgTa                7
minTa                0
minTaHrmt            0
maxTa                0
maxTaHrmt            0
mi10MaxRn         2886
mi10MaxRnHrmt     3059
hr1MaxRn          2884
hr1MaxRnHrmt      3036
sumRnDur          3650
sumRn             2551
maxInsWs             0
maxInsWsWd           0
maxInsWsHrmt         0
maxWs                0
maxWsWd              0
maxWsHrmt            0
avgWs                0
hr24SumRws           0
maxWd               12
avgTd                8
minRhm               0
minRhmHrmt           0
avgRhm               7
avgPv                8
avgPa               11
maxPs                4
maxPsHrmt            4
minPs                5
minPsHrmt            4
avgPs               12
ssDur                0
sumSsHr             17
hr1MaxIcsrHrmt       2
hr1MaxIcsr           2
sumGsr               5
ddMefs            3651
ddMefsHrmt        3651
ddMes             3650
ddMesHrmt         3650
sumDpthFhsc       3651
avgTca            2256
avgLmac           2281
avgTs               18
minTg               18
avgCm5Te            41
avgCm10Te           39
avgCm20Te           40
avgCm30Te           50
avgM05Te          3652
avgM10Te          3652
avgM15Te          3652
avgM30Te          3652
avgM50Te          3652
sumLrgEv          1511
sumSmlEv          1511
n99Rn             3651
iscs              3652
sumFogDur         3652
dtype: int64

In [34]:
data1 = pd.DataFrame(rawData)

data1.drop(['Unnamed: 0', 'stnId', 'stnNm'], axis=1, inplace=True)

# Missing avgTa <- avg. of minTa and maxTa
data1['avgTa'].fillna((data1['minTa'] + data1['maxTa'] / 2), inplace=True)

data1.isna().sum()

tm                   0
avgTa                0
minTa                0
minTaHrmt            0
maxTa                0
maxTaHrmt            0
mi10MaxRn         2886
mi10MaxRnHrmt     3059
hr1MaxRn          2884
hr1MaxRnHrmt      3036
sumRnDur          3650
sumRn             2551
maxInsWs             0
maxInsWsWd           0
maxInsWsHrmt         0
maxWs                0
maxWsWd              0
maxWsHrmt            0
avgWs                0
hr24SumRws           0
maxWd               12
avgTd                8
minRhm               0
minRhmHrmt           0
avgRhm               7
avgPv                8
avgPa               11
maxPs                4
maxPsHrmt            4
minPs                5
minPsHrmt            4
avgPs               12
ssDur                0
sumSsHr             17
hr1MaxIcsrHrmt       2
hr1MaxIcsr           2
sumGsr               5
ddMefs            3651
ddMefsHrmt        3651
ddMes             3650
ddMesHrmt         3650
sumDpthFhsc       3651
avgTca            2256
avgLmac           2281
avgTs               18
minTg               18
avgCm5Te            41
avgCm10Te           39
avgCm20Te           40
avgCm30Te           50
avgM05Te          3652
avgM10Te          3652
avgM15Te          3652
avgM30Te          3652
avgM50Te          3652
sumLrgEv          1511
sumSmlEv          1511
n99Rn             3651
iscs              3652
sumFogDur         3652
dtype: int64

In [36]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3652 entries, 0 to 3651
Data columns (total 60 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tm              3652 non-null   object
 1   avgTa           3652 non-null   float64
 2   minTa           3652 non-null   float64
 3   minTaHrmt       3652 non-null   int64
 4   maxTa           3652 non-null   float64
 5   maxTaHrmt       3652 non-null   int64
 6   mi10MaxRn       766 non-null    float64
 7   mi10MaxRnHrmt   593 non-null    float64
 8   hr1MaxRn        768 non-null    float64
 9   hr1MaxRnHrmt    616 non-null    float64
 10  sumRnDur        2 non-null      float64
 11  sumRn           1101 non-null   float64
 12  maxInsWs        3652 non-null   float64
 13  maxInsWsWd      3652 non-null   int64
 14  maxInsWsHrmt    3652 non-null   int64
 15  maxWs           3652 non-null   float64
 16  maxWsWd         3652 non-null   int64
 17  maxWsHrmt       3652 non-null   int64
 18  avgWs           3652 non-null   float64
 19  hr24SumRws      3652 non-null   int64
 20  maxWd           3640 non-null   float64
 21  avgTd           3644 non-null   float64
 22  minRhm          3652 non-null   int64
 23  minRhmHrmt      3652 non-null   int64
 24  avgRhm          3645 non-null   float64
 25  avgPv           3644 non-null   float64
 26  avgPa           3641 non-null   float64
 27  maxPs           3648 non-null   float64
 28  maxPsHrmt       3648 non-null   float64
 29  minPs           3647 non-null   float64
 30  minPsHrmt       3648 non-null   float64
 31  avgPs           3640 non-null   float64
 32  ssDur           3652 non-null   float64
 33  sumSsHr         3635 non-null   float64
 34  hr1MaxIcsrHrmt  3650 non-null   float64
 35  hr1MaxIcsr      3650 non-null   float64
 36  sumGsr          3647 non-null   float64
 37  ddMefs          1 non-null      float64
 38  ddMefsHrmt      1 non-null      float64
 39  ddMes           2 non-null      float64
 40  ddMesHrmt       2 non-null      float64
 41  sumDpthFhsc     1 non-null      float64
 42  avgTca          1396 non-null   float64
 43  avgLmac         1371 non-null   float64
 44  avgTs           3634 non-null   float64
 45  minTg           3634 non-null   float64
 46  avgCm5Te        3611 non-null   float64
 47  avgCm10Te       3613 non-null   float64
 48  avgCm20Te       3612 non-null   float64
 49  avgCm30Te       3602 non-null   float64
 50  avgM05Te        0 non-null      float64
 51  avgM10Te        0 non-null      float64
 52  avgM15Te        0 non-null      float64
 53  avgM30Te        0 non-null      float64
 54  avgM50Te        0 non-null      float64
 55  sumLrgEv        2141 non-null   float64
 56  sumSmlEv        2141 non-null   float64
 57  n99Rn           1 non-null      float64
 58  iscs            0 non-null      float64
 59  sumFogDur       0 non-null      float64
dtypes: float64(50), int64(9), object(1)
memory usage: 1.7+ MB